### ISSUE TITLE
Should Compare with cch1/http.async.client

### ISSUE THREAD

**Issue by paulrd** [funcool/httpurr#4]
I know there's probably too many clients to compare to, but at first glance cch1/http.async.client seems to cover much of your use case. It is a wrapper over a java async http library (http://github.com/AsyncHttpClient/async-http-client) so it seems more heavyweight and suffers from more incidental abstraction probably. I might try dropping your library in my project to see if it simplifies things.

**Comment by niwinz** [comment]
Take cara that httpur is for clojurescript and not for clojure, but we are considering making it cross platform (because adding support to new "backends" is pretty easy).

**Comment by ghost** [comment]
If we end up supporting Clojure too, which should be easy due to the design of the library, we'll make sure to mention it. Thanks for reporting!

**Comment by paulrd** [comment]
Ah! Yes, I missed that this was Clojurescript! Thanks.
